#config_version=6
#attract mode config file
mode:
  game_mode: False
  # ... other mode settings

ball_holds:
  attract_lock_hold_front:
    balls_to_hold: 1 # MPF will hold up to 2 balls
    hold_devices: bd_trough_front
    enable_events: mode_attract_started #machine_reset_complete # Enables the hold when the machine starts/resets
    disable_events: mode_base_started # Disables the hold when a game starts
    release_one_events: balldevice_bd_trough_front_ball_count_changed{balls>=3}
    # release_all_events: game_starting # Optional: Ejects any held balls when a game starts
  attract_lock_hold_back:
    balls_to_hold: 1 # MPF will hold up to 2 balls
    hold_devices: bd_trough_back
    enable_events: mode_attract_started #machine_reset_complete # Enables the hold when the machine starts/resets
    disable_events: mode_base_started # Disables the hold when a game starts
    release_one_events: balldevice_bd_trough_back_ball_count_changed{balls>=3}
    # release_all_events: game_starting # Optional: Ejects any held balls when a game starts

show_player:
    mode_attract_started: 
        last_game_segment_display:
            action: play        
        attract_light_show_gi:
            speed: 1
            priority: 1        
        attract_display_loop:
            speed: 1
            priority: 2
        attract_light_show:
            speed: 8
            priority: 4
        quickflashColor:
            speed: 1
            show_tokens:
                color: red
                led: l_p1_game over, l_p2_game over
        sequenceColor:
            speed: 6
            priority: 5
            show_tokens:
                color: tt_white
                led: l_p1_2xmulti, l_p1_hunter1, l_p1_50k5eggs, l_p1_dtl40k, l_p1_collect_egg_bonus, l_p1_r3b50k 
                ledB: l_p1_3xmulti, l_p1_hunter2, l_p1_extra_ball, l_p1_dtl80k, l_p1_r3b100k, l_p1_release
                ledC: l_p1_5xmulti, l_p1_hunter3, l_p1_unlimited_balls, l_p1_dtl160k, l_p1_spinner1k, l_p1_r3b150k
                ledD: l_p1_dtl320k, l_p1_r3b200k, l_p1_release, l_p1_spinner5k
        sequenceColor1:
            speed: 6
            priority: 6
            show_tokens:
                color: blue
                led: l_p1_eject20k, l_p2_eject20k
                ledB: l_p1_eject30k, l_p2_eject30k
                ledC: l_p1_eject50k, l_p2_eject50k
                ledD: l_p1_eject_hole, l_p2_eject_hole
        sequenceColor2:
            speed: 6
            priority: 7
            show_tokens:
                color: tt_white
                led: l_p2_2xmulti, l_p2_hunter1, l_p2_50k5eggs, l_p2_dtl40k, l_p2_collect_egg_bonus, l_p2_r3b50k 
                ledB: l_p2_3xmulti, l_p2_hunter2, l_p2_extra_ball, l_p2_dtl80k, l_p2_r3b100k, l_p2_release
                ledC: l_p2_5xmulti, l_p2_hunter3, l_p2_unlimited_balls, l_p2_dtl160k, l_p2_spinner1k, l_p2_r3b150k
                ledD: l_p2_dtl320k, l_p2_r3b200k, l_p2_release, l_p2_spinner5k 
