#config_version=6
lights:
  l_right_flipper1:
    previous: l_neoseg_2d_3_0_f
    type: rgb
  l_right_flipper2:
    previous: l_right_flipper1
    type: rgb
  l_launch:
    previous: l_right_flipper2
    type: rgb
  l_start:
    previous: l_launch
    type: rgb
  l_left_flipper1:
    previous: l_start
    type: rgb
  l_left_flipper2:
    previous: l_left_flipper1
    type: rgb